volumes:
  pg_data:

services:
  db:
    image: postgres:17
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: .
    env_file: .env
    depends_on:
      - db

  gateway:
    build: ./nginx/
    env_file: .env
    ports:
      - 8000:80
    volumes:
      - ./docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend
