"""add meetings

Revision ID: 503e619925fa
Revises: 8f8cc3c59268
Create Date: 2025-09-11 10:47:34.924770

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '503e619925fa'
down_revision: Union[str, Sequence[str], None] = '8f8cc3c59268'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'meeting',
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('description', sa.String(length=4000), nullable=False),
        sa.Column('company_id', sa.Integer(), nullable=False),
        sa.Column('organizer_id', sa.Integer(), nullable=False),
        sa.Column('start_at', sa.DateTime(), nullable=False),
        sa.Column('end_at', sa.DateTime(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.CheckConstraint('end_at > start_at', name='meeting_time_valid'),
        sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['organizer_id'], ['user.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'meetingattendee',
        sa.Column('meeting_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['meeting_id'], ['meeting.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('meeting_id', 'user_id', name='unique_meeting_user'),
    )
    op.create_table(
        'rating',
        sa.Column('task_id', sa.Integer(), nullable=False),
        sa.Column('timeliness', sa.SmallInteger(), nullable=False),
        sa.Column('completeness', sa.SmallInteger(), nullable=False),
        sa.Column('quality', sa.SmallInteger(), nullable=False),
        sa.Column(
            'avg',
            sa.Float(),
            sa.Computed('(timeliness + completeness + quality) / 3.0', persisted=True),
            nullable=False,
        ),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['task_id'], ['task.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('task_id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rating')
    op.drop_table('meetingattendee')
    op.drop_table('meeting')
    # ### end Alembic commands ###
