"""create_company_tables

Revision ID: 7e4771b7fed5
Revises: b6d1d0945b8a
Create Date: 2025-09-04 12:24:14.268803

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7e4771b7fed5'
down_revision: Union[str, Sequence[str], None] = 'b6d1d0945b8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'company',
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('admin_id', sa.Integer(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['admin_id'],
            ['user.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
    )
    op.create_table(
        'department',
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('company_id', sa.Integer(), nullable=False),
        sa.Column('parent_id', sa.Integer(), nullable=True),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['company_id'],
            ['company.id'],
        ),
        sa.ForeignKeyConstraint(
            ['parent_id'],
            ['department.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'usercompanymembership',
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('company_id', sa.Integer(), nullable=False),
        sa.Column('department_id', sa.Integer(), nullable=True),
        sa.Column('manager_id', sa.Integer(), nullable=True),
        sa.Column('role', sa.Enum('USER', 'MANAGER', 'ADMIN', name='user_role'), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['company_id'],
            ['company.id'],
        ),
        sa.ForeignKeyConstraint(
            ['department_id'],
            ['department.id'],
        ),
        sa.ForeignKeyConstraint(
            ['manager_id'],
            ['user.id'],
        ),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['user.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'company_id', name='unique_user_company'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usercompanymembership')
    op.drop_table('department')
    op.drop_table('company')
    # ### end Alembic commands ###
