"""remove_news_unique_constraint

Revision ID: 140b0fc09f14
Revises: 5e9749f7e733
Create Date: 2025-09-05 13:05:06.518488

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '140b0fc09f14'
down_revision: Union[str, Sequence[str], None] = '5e9749f7e733'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('unique_title_published'), 'companynews', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f('unique_title_published'), 'companynews', ['title', 'published_at'], postgresql_nulls_not_distinct=False
    )
    # ### end Alembic commands ###
