"""remove_news_auto_datetime

Revision ID: c0b0cc3c14ff
Revises: 140b0fc09f14
Create Date: 2025-09-05 13:36:24.898486

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = 'c0b0cc3c14ff'
down_revision: Union[str, Sequence[str], None] = '140b0fc09f14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
