"""create task and task_comment

Revision ID: b6a14d852177
Revises: 02a8437c1432
Create Date: 2025-09-09 17:20:40.751289

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b6a14d852177'
down_revision: Union[str, Sequence[str], None] = '02a8437c1432'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invite', sa.Column('expires_at', sa.DateTime(), nullable=False))
    op.drop_index(op.f('ix_invite_code'), table_name='invite')
    op.create_index(op.f('ix_invite_expires_at'), 'invite', ['expires_at'], unique=False)
    op.create_unique_constraint(None, 'invite', ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invite', type_='unique')
    op.drop_index(op.f('ix_invite_expires_at'), table_name='invite')
    op.create_index(op.f('ix_invite_code'), 'invite', ['code'], unique=True)
    op.drop_column('invite', 'expires_at')
    # ### end Alembic commands ###
