"""update invite

Revision ID: 02a8437c1432
Revises: 140b0fc09f14
Create Date: 2025-09-08 22:37:19.333226

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '02a8437c1432'
down_revision: Union[str, Sequence[str], None] = '140b0fc09f14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invite', sa.Column('email', sa.String(length=320), nullable=False))
    op.add_column('invite', sa.Column('manager_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('invite_code_key'), 'invite', type_='unique')
    op.create_index(op.f('ix_invite_code'), 'invite', ['code'], unique=True)
    op.drop_constraint(op.f('invite_created_by_fkey'), 'invite', type_='foreignkey')
    op.create_foreign_key(None, 'invite', 'user', ['manager_id'], ['id'], ondelete='SET NULL')
    op.drop_column('invite', 'created_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invite', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'invite', type_='foreignkey')
    op.create_foreign_key(op.f('invite_created_by_fkey'), 'invite', 'user', ['created_by'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_invite_code'), table_name='invite')
    op.create_unique_constraint(op.f('invite_code_key'), 'invite', ['code'], postgresql_nulls_not_distinct=False)
    op.drop_column('invite', 'manager_id')
    op.drop_column('invite', 'email')
    # ### end Alembic commands ###
