AUTH_PREFIX = '/auth/jwt'
TOKEN_URL = f'{AUTH_PREFIX}/login'
MIN_LEN_PASSWORD = 6
JWT_LIFETIME = 60 * 60

COMPANY_NAME_MAX_LENGTH = 255
DEPARTMENT_NAME_MAX_LENGTH = 255
NEWS_TITLE_MAX_LENGTH = 255
NEWS_BODY_MAX_LENGTH = 4000
