AUTH_PREFIX = '/auth/jwt'
SWAGGER_TOKEN_URL = f'/api/v1{AUTH_PREFIX}/login'
MIN_LEN_PASSWORD = 6
JWT_LIFETIME = 60 * 60

COMPANY_NAME_MAX_LENGTH = 255
DEPARTMENT_NAME_MAX_LENGTH = 255
NEWS_TITLE_MAX_LENGTH = 255
NEWS_BODY_MAX_LENGTH = 4000

INVITE_CODE_LENGTH = 6
INVITE_CODE_CHARS = '0123456789'
MAX_INVITE_CODE_ATTEMPTS = 5
